# Generated by Django 3.0.6 on 2020-05-22 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('total_workers', models.IntegerField(blank=True)),
                ('male_coolie', models.IntegerField()),
                ('female_coolie', models.IntegerField(blank=True)),
                ('mason', models.IntegerField(blank=True)),
                ('centric_fitter', models.IntegerField(blank=True)),
                ('material_details', models.TextField(null=True)),
                ('materials_purchased', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daily_update.Materials')),
                ('siteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_sites.AddSites')),
            ],
        ),
    ]
