# Generated by Django 3.0.6 on 2020-05-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdate',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
