# Generated by Django 3.0.6 on 2020-05-22 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_sites', '0001_initial'),
        ('daily_update', '0002_auto_20200522_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdate',
            name='siteid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_sites.AddSites'),
        ),
    ]
